Clean up of functional_test

diff --git a/bin/functional_test b/bin/functional_test
--- a/bin/functional_test
+++ b/bin/functional_test
@@ -5,9 +5,10 @@
 
 set -e
 
-VERSION=0.0.1
-ARTIFACT=jar3d-$VERSION-SNAPSHOT.jar
-MODELS=~/groups
+VERSION="0.0.1"
+ARTIFACT="jar3d-$VERSION-SNAPSHOT.jar"
+RESOURCES="src/test/resources"
+MODELS="$RESOURCES/models"
 
 function compare {
   computed=$1
@@ -15,18 +16,27 @@ function compare {
   type=$3
   tmp=`mktemp /tmp/jar3d-XXXXXX`
 
-  set +e
-  diff $computed $correct > $tmp
+  # Check that the answer file exists.
+  if [[ ! -e "$correct" ]]; then
+    echo "Can't find $correct to compare to"
+    exit 1
+  fi
 
+  # Set +e so we display an error message when diff fails.
+  set +e
+  diff "$computed" "$correct" > "$tmp"
+
+  # Copy the diff, show a message and die.
   if [[ $? -ne 0 ]]; then
     diffs=target/diff.txt
-    cat $tmp
-    cp $tmp $diffs
+    cp "$tmp" "$diffs"
     echo "TEST FAILURE. Expected and computed $type results do not match"
     echo "  See: $diffs"
     exit 1
   fi
 
+  # Clean up
+  rm $tmp
   set -e
 }
 
@@ -40,26 +50,30 @@ function run {
   # This line executes the JAR3D executable. -Xmx500m is used to raise the
   # memory limit of the JVM. In some cases it needs more memory than the
   # default limit.
-  echo "Command: 'java -Xmx500m -jar target/$ARTIFACT $sequences $MODELS $loop_results $sequence_results'"
-  java -Xmx500m -jar target/$ARTIFACT $sequences $MODELS $loop_results $sequence_results
+  cmd="java -Xmx500m -jar target/$ARTIFACT $sequences $MODELS $loop_results $sequence_results"
+  echo "Command: '$cmd'"
+  $cmd
 
+  # Check that the results are correct for loops and sequences
   compare $loop_results $loop_answers "loop"
   compare $sequence_results $sequence_answers "sequence"
 
-  rm $loop_results $sequence_answers
+  # Clean up
+  rm $loop_results $sequence_results
 }
 
 # Compile JAR3D using Maven
-echo "Building JAR3D: 'mvn clean package'"
-mvn clean package > /dev/null
+cmd='mvn clean package'
+echo "Building JAR3D: '$cmd'"
+$cmd > /dev/null
 
-# Run JAR3D on test data with some simple models
-sequences=~/lab/code/seq-var/tmp/IL_1L9A_006.fasta
-for sequences in "src/test/resources/test-data/*.fasta"; do
+# Run JAR3D on test data
+test_files="$RESOURCES/test-data"
+for sequences in "$test_files/*.fasta"; do
 
   base=`basename $sequences .fasta`
-  loop_answer=$base-loops.csv
-  sequence_answer=$base-sequences.csv
+  loop_answer=$test_files/$base-loops.csv
+  sequence_answer=$test_files/$base-sequences.csv
 
   echo "Testing with: $sequences"
   run $sequences $loop_answer $sequence_answer
